language: java
script: ant main
sudo: false
matrix:
  fast_finish: true
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8
      before_install:
        - brew update
        - brew install ant
